CC=gcc
CFLAGS=-I.


all: program1 program2 program3 program4 

program1: 12-16.c 
	gcc -o 12-16 12-16.c 

program2: 12-17.c 
	gcc -o 12-17 12-17.c 


program3: dotpr-hw.c 
	gcc -o dotpr-hw dotpr-hw.c 

program4: hello-hw.c 
	gcc -o hello-hw hello-hw.c 

clean:
	rm 12-16 12-17 dotpr-hw hello-hw
